#+TITLE: Articles
#+AUTHOR: Tony aldon

* [2019-05-12 Sun] Des hauts et des bas

Dans la vie, il y a des hauts et des bas.

Aujourd'hui, c'est un bas pour le père que je suis.  La mère de mon
enfant vient de m'en retirer la garde.  À partir d'aujourd'hui, mon
fils ne pourra me voir que la moitié des vacances scolaires.  Ce qui
correspond à 8 semaines par an.

: Soyons plus précis, dans 7 ans, mon fils aura 14 ans, et à la fin de
: ces 7 années, il ne m'aura vu qu'UNE année.

Je suis triste pour mon fils bien plus que pour moi.  Car je suis déjà
un adulte, mais je sais que lui, enfant, a encore autant besoin de son
père que de sa mère pour pouvoir grandir et s'épanouir.

*Si vous me demandez, en veux-tu à la mère de ton enfant?*

Je vous répondrai non sans hésiter.  Je pense seulement qu'elle se
trompe.  Je pense seulement qu'elle a oublié le bonheur de son enfant
en prenant cette décision.  Je pense plein de chose, mais non je ne lui
en veux pas.  Je suis seulement triste.

*Si vous me demandez, en veux-tu à la justice?*

Je vous répondrai non sans hésiter.  La justice prend seulement les
décisions qu'on lui demande de prendre en appliquant des lois venues
le plus souvent d'époques lointaines.

Et le point important est bien là.  Le peuple, NOUS, nous faisons les
lois et nous demandons qu'elles soient appliquées.  Et aujourd'hui,
c'est bien la mère de mon enfant qui a demandé à la justice que mon
enfant ne me voit presque plus.

*Si vous me demandez...*

Je vous dirai que l'un des fondements du bonheur d'un enfant vient du
temps qu'il a passé avec ses parents, à recevoir de l'amour de
ceux-ci, à partager avec eux des moments qui resteront inoubliables,
gravés dans sa mémoire.

Et si la construction de ce bonheur se fait correctement, un jour, cet
enfant devenu adulte, pourra regarder le passé, son passé, son enfance
avec douceur, et voir tous ces moments heureux passés avec ses
parents.

Si vous êtes un parent, quand l'heure de prendre une décision comme
celle de priver votre enfant de voir son autre parent; Pensez toujours
en premier au bonheur de votre enfant, quoi-qu'il vous en coûte.

Si vous êtes seulement un enfant, et nous sommes tous les enfants de
quelqu'un, je vous invite à penser à tous les bons moments que vous
avez passés dans votre enfance avec vos parents; une glace, un jour
ensoleillé, une promenade, des éclats de rire, un pain au chocolat à
la sortie de l'école...

*Si vous me demandez ce que je vais faire maintenant?*

Je vais continuer à vivre.  Je vais continuer à aimer la vie.  Je vais
continuer à aimer mon fils d'un amour éternel et inconditionnel.  Je
vais continuer à...

Dans la vie, il y a des hauts et des bas.

Qu'importe les bas, je ne vis que pour les hauts.

Je t'aime mon fils.

ps: je suis sûr qu'à la lecture de cet article, vous avez pensé à un
proche, un ami, un parent...  Partagez cet article avec lui.  Prenez le
temps de le contacter, parlez-lui.
